[project]
name = "cardmarket"
version = "0.1.0"
description = ""
authors = [
    {name = "Roman",email = "Spctrl82@yandex.ru"}
]
requires-python = ">=3.14"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ["py314"]

[tool.isort]
profile = "black"
skip = ["venv", ".venv", "__pycache__", "build", "dist"]

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
exclude = [".git", "__pycache__", "venv", ".venv", "build", "dist"]

[tool.mypy]
python_version = "3.14"
warn_return_any = true
disallow_untyped_defs = true
ignore_missing_imports = true
files = ["templates"]